repositories:
  - name: concourse
    url: https://raw.githubusercontent.com/concourse/charts/gh-pages
  - name: harbor
    url: https://helm.goharbor.io
  - name: confluentinc
    url: https://confluentinc.github.io/cp-helm-charts/
  - name: gitlab
    url: https://charts.gitlab.io/
  - name: loki
    url: https://grafana.github.io/loki/charts

helmDefaults:
  timeout: 600
  recreatePods: true
  # tillerless: true
  kubeContext: {{ requiredEnv "CLUSTER_NAME" }}

releases:
  # - name: deluge
  #   chart: ./deluge/deluge
  #   namespace: deluge

  # Nginx Ingress and MetalLB
  - name: nginx-ingress
    chart: stable/nginx-ingress
    namespace: ingress-nginx
    values:
      - controller:
          extraArgs:
            default-ssl-certificate: "ingress-nginx/default-ssl-certificate"
          service:
            loadBalancerIP: {{ requiredEnv "INGRESS_STATIC_IP" }}
          publishService:
            enabled: true

          metrics:
            enabled: true

            # Specifically for the Prometheus Operator
            serviceMonitor:
              enabled: true
              namespace: "monitoring"
              additionalLabels:
                prometheus: monitoring
              # honorLabels: true

        podSecurityPolicy:
          enabled: true

        tcp:
          22: "gitlab-system/gitlab-gitlab-shell:22" # Git SSH
          6514: "monitoring/fluentd:6514"            # syslog forwarding

        # udp:
        #   514: "monitoring/fluentd:514"            # syslog forwarding

  - name: metallb
    chart: stable/metallb
    namespace: metallb-system
    values:
      - configInline:
          address-pools:
            - name: default
              protocol: layer2
              addresses:
                - {{ requiredEnv "LOAD_BALANCER_IP_RANGE" }}

        psp:
          create: true

  - name: harbor-postgres
    chart: stable/postgresql
    namespace: harbor-system
    values:
      - databases/postgres-base.yaml.gotmpl
      - global:
          postgresql:
            existingSecret: harbor-postgres-postgresql-admin

        postgresqlDatabase: registry

        persistence:
          existingClaim: data-harbor-postgres-postgresql-0

        initdbScripts:
          db-init.sql: |
            CREATE DATABASE notary_server;
            CREATE DATABASE notary_signer;
            CREATE DATABASE clair;

  #! Harbor
  - name: harbor
    chart: ../harbor-helm
    namespace: harbor-system
    values:
      - harbor/values.yaml.gotmpl

  #! Concourse and Concourse Postgres Database.
  - name: postgres
    chart: stable/postgresql
    namespace: concourse-system
    values:
      - databases/postgres-base.yaml.gotmpl
      - global:
          postgresql:
            existingSecret: concourse-postgres-postgresql-admin

        persistence:
          existingClaim: data-postgres-postgresql-0

        postgresqlDatabase: atc

  - name: concourse
    chart: ../charts/stable/concourse
    namespace: concourse-system
    values:
      - concourse/values.yaml.gotmpl

  #! GitLab, GitLab Postgres Database, and GitLab Runner.
  #! See https://docs.gitlab.com/charts/installation/version_mappings.html
  - name: gitlab
    chart: gitlab/gitlab
    namespace: gitlab-system
    recreatePods: false
    values:
      - gitlab/values.yaml.gotmpl

  - name: gitlab-postgres
    chart: stable/postgresql
    namespace: gitlab-system
    values:
      - databases/postgres-base.yaml.gotmpl
      - gitlab/postgres-values.yml.gotmpl

  - name: gitlab-runner
    chart: gitlab/gitlab-runner
    namespace: gitlab-runner
    values:
      - gitlab/gitlab-runner-values.yaml.gotmpl

  # Minio
  - name: minio
    chart: stable/minio
    namespace: minio-system
    values:
      - image:
          repository: minio/minio
          tag: edge

        nasgateway:
          enabled: true
          replicas: 1
          pv: {{ requiredEnv "MINIO_PVC_LABEL" }}

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - {{ requiredEnv "MINIO_DNS" }}
          tls:
            - hosts:
                - {{ requiredEnv "MINIO_DNS" }}

        persistence:
          accessMode: ReadWriteOnce
          size: 100Gi
        # environment:
        #   MINIO_HTTP_TRACE: /dev/stdout
        accessKey: {{ requiredEnv "MINIO_ACCESS_KEY" }}
        secretKey: {{ requiredEnv "MINIO_SECRET_KEY" }}

  # Observability
  - name: monitoring
    chart: stable/prometheus-operator
    namespace: monitoring
    values:
      - monitoring/prometheus-operator-values.yaml.gotmpl

  - name: snmp
    chart: stable/prometheus-snmp-exporter
    namespace: monitoring
    values:
      - monitoring/snmp-config.yaml.gotmpl
      - monitoring/snmp-values.yaml.gotmpl

  - name: loki
    chart: loki/loki
    namespace: monitoring
    values:
      - persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 300Gi
          storageClassName: {{ requiredEnv "STORAGE_CLASS_NAME" }}

  - name: fluentd
    chart: stable/fluentd
    namespace: monitoring
    recreatePods: false
    values:
      - monitoring/fluentd-values.yaml.gotmpl