{
 "title": "Concourse",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "query": "label_values(concourse_builds_duration_seconds_sum{service=\"concourse-web\"}, team)\t"
   },
   {
    "name": "pipeline",
    "query": "label_values(concourse_builds_duration_seconds_sum{service=\"concourse-web\", team=~\"$team\"}, pipeline)\t"
   }
  ]
 },
 "panels": [
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Concourse Worker Containers Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(concourse_workers_containers) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Concourse Worker Volumes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(concourse_workers_volumes) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  { "title": "Build Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Build Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(concourse_builds_duration_seconds_count{team=~\"$team\", pipeline=~\"$pipeline\"}) by (pipeline)",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  { "title": "Build Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Concourse Builds Duration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(irate(concourse_builds_duration_seconds_sum{team=~\"$team\", pipeline=~\"$pipeline\",service=\"concourse-web\"}[5m])) by (le)"
    }
   ]
  },
  {
   "title": "Concourse All Builds Duration Quantiles",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(concourse_builds_duration_seconds_bucket{team=~\"$team\", pipeline=~\"$pipeline\", service=\"concourse-web\"}[10m])) by (le))",
     "legendFormat": "99p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(concourse_builds_duration_seconds_bucket{team=~\"$team\", pipeline=~\"$pipeline\", service=\"concourse-web\"}[10m])) by (le))",
     "legendFormat": "90p"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(concourse_builds_duration_seconds_bucket{team=~\"$team\", pipeline=~\"$pipeline\", service=\"concourse-web\"}[10m])) by (le))",
     "legendFormat": "50p"
    }
   ]
  }
 ]
}