{
 "title": "Namespace cost & utilization metrics",
 "description": "A dashboard to help with cost and utilisation",
 "tags": [
  "cost",
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "costcpu", "label": "CPU", "query": "23.06" },
   { "name": "costpcpu", "label": "PE CPU", "query": "7.28" },
   { "name": "costram", "label": "RAM", "query": "3.25" },
   { "name": "costpram", "label": "PE RAM", "query": "0.6862" },
   { "name": "costStorageStandard", "label": "Storage", "query": "0.04" },
   { "name": "costStorageSSD", "label": "SSD", "query": ".17" },
   { "name": "costDiscount", "label": "Disc.", "query": "30" },
   {
    "name": "namespace",
    "label": "NS",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod cost and utilisation analysis",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\n sum(container_spec_cpu_shares{namespace=\"$namespace\",cloud_google_com_gke_preemptible!=\"true\"}/1000*($costcpu - ($costcpu / 100 * $costDiscount))) by(pod_name)\n or\n count(\n count(container_spec_cpu_shares{namespace=\"$namespace\"}) by(pod_name)\n ) by(pod_name) -1\n)\n\n+\n\n(\n sum(container_spec_cpu_shares{namespace=\"$namespace\",cloud_google_com_gke_preemptible=\"true\"}/1000*$costpcpu) by(pod_name)\n or\n count(\n count(container_spec_cpu_shares{namespace=\"$namespace\"}) by(pod_name)\n ) by(pod_name) -1\n)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "sum(\n count(count(container_spec_cpu_shares{namespace=\"$namespace\"}) by (pod_name)) by (pod_name) \n * on (pod_name) \n sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) by (pod_name)\n) by (pod_name) * 1000\n/\nsum(container_spec_cpu_shares{namespace=\"$namespace\"}) by (pod_name) * 100",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "(\n sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",cloud_google_com_gke_preemptible!=\"true\"}/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by(pod_name)\n or\n count(\n count(container_spec_memory_limit_bytes{namespace=\"$namespace\"}) by(pod_name)\n ) by(pod_name) -1\n)\n\n+\n\n(\n sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",cloud_google_com_gke_preemptible=\"true\"}/1024/1024/1024*$costpram) by(pod_name)\n or\n count(\n count(container_spec_memory_limit_bytes{namespace=\"$namespace\"}) by(pod_name)\n ) by(pod_name) -1\n)",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(\n count(count(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod_name)) by (pod_name) \n * on (pod_name) \n sum(avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\"}[1m])) by (pod_name)\n) by (pod_name)\n/\nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\"}) by (pod_name) * 100",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "(\n sum(container_spec_cpu_shares{namespace=\"$namespace\",cloud_google_com_gke_preemptible!=\"true\"}/1000*($costcpu - ($costcpu / 100 * $costDiscount))) by(pod_name)\n or\n count(\n count(container_spec_cpu_shares{namespace=\"$namespace\"}) by(pod_name)\n ) by(pod_name) -1\n)\n\n+\n\n(\n sum(container_spec_cpu_shares{namespace=\"$namespace\",cloud_google_com_gke_preemptible=\"true\"}/1000*$costpcpu) by(pod_name)\n or\n count(\n count(container_spec_cpu_shares{namespace=\"$namespace\"}) by(pod_name)\n ) by(pod_name) -1\n)\n\n# Now ram\n\n+ \n(\n sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",cloud_google_com_gke_preemptible!=\"true\"}/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by(pod_name)\n or\n count(\n count(container_spec_memory_limit_bytes{namespace=\"$namespace\"}) by(pod_name)\n ) by(pod_name) -1\n)\n\n+\n\n(\n sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",cloud_google_com_gke_preemptible=\"true\"}/1024/1024/1024*$costpram) by(pod_name)\n or\n count(\n count(container_spec_memory_limit_bytes{namespace=\"$namespace\"}) by(pod_name)\n ) by(pod_name) -1\n)\n\n"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum (\n sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim, namespace)\n) by (namespace,persistentvolumeclaim,storageclass) / 1024 / 1024 /1024 * $costStorageSSD\n\nor\n\nsum (\n sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim, namespace)\n) by (namespace,persistentvolumeclaim,storageclass) / 1024 / 1024 /1024 * $costStorageStandard\n",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Ratio of CPU requests to usage (by container)",
   "type": "graph",
   "description": "CPU requests by container divided by the rate of CPU usage over the last hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, label_replace(\n label_replace(\n kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"},\n \"pod_name\", \n \"$1\", \n \"pod\", \n \"(.+)\"\n ),\n \"container_name\", \n \"$1\", \n \"container\", \n \"(.+)\"\n) \n/\non(pod_name,container_name) \nsum(\n rate(\n container_cpu_usage_seconds_total{namespace=\"$namespace\",pod_name=~\".+\"}[1h]\n )\n) \nby (pod_name,container_name))"
    }
   ]
  },
  {
   "title": "Overall CPU Utilisation",
   "type": "graph",
   "description": "This panel shows historical utilisation as an average across all pods in this namespace. It only accounts for currently deployed pods",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\"}[10m])) by (namespace) * 1000\n/\nsum(avg_over_time(container_spec_cpu_shares{namespace=\"$namespace\"}[10m])) by (namespace) * 100",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Overall RAM Utilisation",
   "type": "graph",
   "description": "This panel shows historical utilisation as an average across all pods in this namespace. It only accounts for currently deployed pods",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\"}) by (namespace)\n/\nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\"}) by (namespace) * 100",
     "legendFormat": "limit utilization"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\"}) by (namespace)\n/\nsum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (namespace) * 100",
     "legendFormat": "request utilization"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "description": "Traffic in and out of this namespace, as a sum of the pods within it",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "<- in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Disk reads and writes for the namespace, as a sum of the pods within it",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_writes_bytes_total{namespace=\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "<- write"
    },
    {
     "expr": "- sum (rate (container_fs_reads_bytes_total{namespace=\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "-> read"
    }
   ]
  }
 ]
}