apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd
    heritage: manual
    release: fluentd
  name: fluentd-udp
  namespace: monitoring
spec:
  loadBalancerIP: 192.168.2.51
  ports:
  - name: unifi-syslog
    port: 514
    protocol: UDP
    targetPort: 514
  selector:
    app: fluentd
    release: fluentd
  type: LoadBalancer