---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-database
  labels:
    type: vmdk
    storage: disk
    name: gitlab-database
    app: gitlab
    release: gitlab
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "[storage01] volumes/gitlab-database"
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-database
  namespace: gitlab-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: gitlab-database
      type: vmdk
