global:
  postgresql:
    existingSecret: gitlab-postgres-postgresql
volumePermissions:
  enabled: true

securityContext:
  enabled: true
  fsGroup: 1000
  runAsUser: 1000

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## If defined, PVC must be created manually before volume will be bound
  ## The value is evaluated as a template, so, for example, the name can depend on .Release or .Chart
  ##
  existingClaim: gitlab-database

  accessModes:
    - ReadWriteOnce
  size: 10Gi

metrics:
  enabled: true

  securityContext:
    enabled: true
    runAsUser: 1000

postgresqlDatabase: gitlab