apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vsphere-volume
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters:
  datastore: storage01
